version: '3.8'

services:
  postgres:
    image: postgres:12.2
    ports:
      - 5432:5432
    volumes:
      - rw-stammdaten:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test
      - PGDATA=/var/lib/postgresql/data/pgdata

  opensearch-node1:
    image: opensearchproject/opensearch:1.2.4
    container_name: opensearch-node1-quarkus
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: opensearch-cluster
      discovery.seed_hosts: opensearch-cluster
      cluster.initial_master_nodes: opensearch-cluster
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  opensearch-dashboards-quarkus:
    image: opensearchproject/opensearch-dashboards:1.2.0
    container_name: opensearch-dashboards-quarkus
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch-node1:9200"]'

volumes:
  rw-stammdaten:

  opensearch-data1: